"""(R function name, instance, dimension) cases for the R parity test."""

import equinox as eqx

import vlse

CASES: list[tuple[str, eqx.Module, int]] = [
    ("ackley", vlse.Ackley(d=5), 5),
    ("bukin6", vlse.Bukin6(), 2),
    ("crossit", vlse.CrossInTray(), 2),
    ("drop", vlse.DropWave(), 2),
    ("egg", vlse.EggHolder(), 2),
    ("grlee12", vlse.GramacyLee(), 1),
    ("griewank", vlse.Griewank(d=5), 5),
    ("holder", vlse.HolderTable(), 2),
    ("langer", vlse.Langermann(), 2),
    ("levy", vlse.Levy(d=5), 5),
    ("levy13", vlse.Levy13(), 2),
    ("rastr", vlse.Rastrigin(d=5), 5),
    ("schaffer2", vlse.Schaffer2(), 2),
    ("schaffer4", vlse.Schaffer4(), 2),
    ("schwef", vlse.Schwefel(d=5), 5),
    ("shubert", vlse.Shubert(), 2),
    ("boha1", vlse.Bohachevsky(variant=1), 2),
    ("boha2", vlse.Bohachevsky(variant=2), 2),
    ("boha3", vlse.Bohachevsky(variant=3), 2),
    ("perm0db", vlse.Perm0(d=4), 4),
    ("rothyp", vlse.RotatedHyperEllipsoid(d=5), 5),
    ("spheref", vlse.Sphere(d=5), 5),
    ("spherefmod", vlse.Sphere(d=6, rescaled=True), 6),
    ("sumpow", vlse.SumPowers(d=5), 5),
    ("sumsqu", vlse.SumSquares(d=5), 5),
    ("trid", vlse.Trid(d=5), 5),
    ("booth", vlse.Booth(), 2),
    ("matya", vlse.Matyas(), 2),
    ("mccorm", vlse.McCormick(), 2),
    ("powersum", vlse.PowerSum(d=4), 4),
    ("zakharov", vlse.Zakharov(d=5), 5),
    ("camel3", vlse.Camel3(), 2),
    ("camel6", vlse.Camel6(), 2),
    ("dixonpr", vlse.DixonPrice(d=5), 5),
    ("rosen", vlse.Rosenbrock(d=5), 5),
    ("rosensc", vlse.Rosenbrock(d=4, rescaled=True), 4),
    ("dejong5", vlse.DeJong5(), 2),
    ("easom", vlse.Easom(), 2),
    ("michal", vlse.Michalewicz(d=5), 5),
    ("beale", vlse.Beale(), 2),
    ("branin", vlse.Branin(), 2),
    ("braninsc", vlse.Branin(rescaled=True), 2),
    ("braninmodif", vlse.Branin(modified=True), 2),
    ("colville", vlse.Colville(), 4),
    ("forretal08", vlse.Forrester(), 1),
    ("forretal08lc", vlse.ForresterLowFidelity(), 1),
    ("goldpr", vlse.GoldsteinPrice(), 2),
    ("goldprsc", vlse.GoldsteinPrice(rescaled=True), 2),
    ("hart3", vlse.Hartmann3(), 3),
    ("hart4", vlse.Hartmann4(), 4),
    # crosswise on purpose: SFU swapped these pages, hart6r.R is the rescaled form
    ("hart6", vlse.Hartmann6(rescaled=True), 6),
    ("hart6sc", vlse.Hartmann6(), 6),
    ("permdb", vlse.Perm(d=4), 4),
    ("powell", vlse.Powell(d=4), 4),
    ("shekel5", vlse.Shekel(m=5), 4),
    ("shekel7", vlse.Shekel(m=7), 4),
    ("shekel10", vlse.Shekel(m=10), 4),
    ("stybtang", vlse.StyblinskiTang(d=5), 5),
]

# shekelr.R hardcodes `m <- 10` and ignores its m argument, so only shekel10 is comparable
KNOWN_R_BUGS = {"shekel5", "shekel7"}
